### PR TITLE
Report/differential analysis 02

### PR DESCRIPTION
**Pull request by cmrn-rhi**
DE2 more stuff done, Cara to check heatmap groupings (sorry for the lack of details).

### CODE REVIEW

**Review by FaezeK — DISMISSED** [review]

**Comment by creisle** [comment]
I am going to work off this branch but

**Review by creisle — CHANGES_REQUESTED** [review]
Just confused on which file we are using now. Why are there two DE analysis files?

**Review by creisle — DISMISSED** [review]

**Comment by FaezeK** [comment]
Is it too much trouble to merge this branch with master? In my recent PR, I added my graphs to .gitignore and I just want to make sure that they'll stay there.

**Comment by creisle** [comment]
> Is it too much trouble to merge this branch with master? In my recent PR, I added my graphs to .gitignore and I just want to make sure that they'll stay there.

I can just resolve the conflicts here :) I'll make sure they stay

**Comment by FaezeK** [comment]
> > Is it too much trouble to merge this branch with master? In my recent PR, I added my graphs to .gitignore and I just want to make sure that they'll stay there.
> 
> I can just resolve the conflicts here :) I'll make sure they stay

That'd be great, thanks

**Comment by cmrn-rhi** [comment]
Hmmm. I updated from master after Faeze's pull request, thought that would address any potential conflicts in the `.gitignore`.

**Comment by FaezeK** [comment]
> Hmmm. I updated from master after Faeze's pull request, thought that would address any potential conflicts in the `.gitignore`.

Awesome, thanks

**Review by FaezeK — APPROVED** [review]

**Pull request merged**
