### PR TITLE
Conor reports

### PR DESCRIPTION
**Pull request by clmorrison**
added my reports and tried to link in the README.

However my links in the README table of contents dont seem to work and im not sure why

### CODE REVIEW

**Comment by FaezeK** [comment]
It seems like there's a conflict in the README

**Comment by creisle** [comment]
fixed links and readme. Your id parameter of you links needs to match the name of the header for it to work

**Comment by creisle** [comment]
did you mean to add the rds file? its huge and we don't need it since its an intermediate file

**Comment by clmorrison** [comment]
my bad, yes let's remove it

**Review by cmrn-rhi — APPROVED** [review]

**Pull request merged**
