### PR TITLE
Feature/de sample lib size

### PR DESCRIPTION
**Pull request by creisle**
This uses the lib.size counts from the original files pre-filtering.

Makes some diff to the top 15 genes (left without, right with)
image

Note that I've done a full diff of before and after printed to pdf if you would like to compare

### CODE REVIEW

**Comment by creisle** [comment]
This branch contains the changes also in master. Will need to merge master into the target branch to see the Rmd changes only

**Comment by FaezeK** [comment]
> This branch contains the changes also in master. Will need to merge master into the target branch to see the Rmd changes only

Do you mind doing a pull and make a new PR, it's a bit confusing to see the previous changes again

**Comment by creisle** [comment]
> Do you mind doing a pull and make a new PR, it's a bit confusing to see the previous changes again

I would need to change the target branch. This one has already been pulled

**Comment by creisle** [comment]
@cmrn-rhi could you update your DE2 branch (pull master then merge master into it)?

**Review by cmrn-rhi — APPROVED** [review]

**Comment by cmrn-rhi** [comment]
> @cmrn-rhi could you update your DE2 branch (pull master then merge master into it)?

K. Will update from master and to another PR.

**Pull request merged**
